#!/bin/bash
#
# Execute 'git pull' for each remote branch

for branch in `git branch -a | grep remotes | grep -v HEAD | grep -v master ` ; do
    git branch --track ${branch#remotes/origin/} $branch
done
