#!/bin/sh
#
# Replace strings in multiple files

if [ $# -lt 3 ] ; then
    echo "usage: $0 <old string> <new string> <file name>"
    echo "  e.g. $0 lang long \"*.txt\""
    exit 1
fi

find . -maxdepth 1 -name "$3" | xargs -n 1 -t sed -i'.bak' "s/$1/$2/g"
