#!/bin/sh
#
# Replace strings in multiple files recursively

if [ $# -lt 3 ] ; then
    echo "usage: $0 <old string> <new string> <file nmae>"
    echo "  e.g. $0 lang long \"*.txt\""
    exit 1
fi

find . -name "$3" | xargs -n 1 -t sed -i'.bak' "s/$1/$2/g"
